// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWalKqdrP6iNrLa6JG34T-prRaFuQnkZI',
    appId: '1:990121102003:web:80dbf854459bce967e3ec6',
    messagingSenderId: '990121102003',
    projectId: 'e-learning-98fdb',
    authDomain: 'e-learning-98fdb.firebaseapp.com',
    storageBucket: 'e-learning-98fdb.appspot.com',
    measurementId: 'G-WM3YVBMPEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1g8Tz-IerwDTRIZsclMwGoW66xZ8ApQw',
    appId: '1:990121102003:android:f433cda43b0fee957e3ec6',
    messagingSenderId: '990121102003',
    projectId: 'e-learning-98fdb',
    storageBucket: 'e-learning-98fdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv2ObmJb1SmT93C2iyZ9txNbuCtPFisAk',
    appId: '1:990121102003:ios:0d0828845e7b8fec7e3ec6',
    messagingSenderId: '990121102003',
    projectId: 'e-learning-98fdb',
    storageBucket: 'e-learning-98fdb.appspot.com',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv2ObmJb1SmT93C2iyZ9txNbuCtPFisAk',
    appId: '1:990121102003:ios:0d0828845e7b8fec7e3ec6',
    messagingSenderId: '990121102003',
    projectId: 'e-learning-98fdb',
    storageBucket: 'e-learning-98fdb.appspot.com',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWalKqdrP6iNrLa6JG34T-prRaFuQnkZI',
    appId: '1:990121102003:web:c9d5d4e1312b8bc77e3ec6',
    messagingSenderId: '990121102003',
    projectId: 'e-learning-98fdb',
    authDomain: 'e-learning-98fdb.firebaseapp.com',
    storageBucket: 'e-learning-98fdb.appspot.com',
    measurementId: 'G-XYS3TJYR4Y',
  );
}
